AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
